### PR TITLE
Restaurant page menu 169566442

### PR DESCRIPTION
**Pull request by Midetech**
Complete the Restaurant Menu Page
screencapture-localhost-3000-2019-11-30-06_20_58

### CODE REVIEW

**Review by bamiogunfemi — APPROVED** [review]
LGTM

**Review by samynaj — APPROVED** [review]
yeah LGTM

**Review by John-pels — APPROVED** [review]
LGTM

**Review by Joggz — APPROVED** [review]
Nice one. Looks Good

**Review by John-pels — CHANGES_REQUESTED** [review]
Work on the mobile responsiveness.

**Comment by bamiogunfemi** [comment]
Please rebase

**Review by John-pels — APPROVED** [review]
LGTM, please rebase

**Pull request closed without merging**
