### PR TITLE
SignIn With Email Auth

### PR DESCRIPTION
**Pull request by bamiogunfemi**
- Implemented Redux
-Implemented sign in loader 
image

### CODE REVIEW

**Review by John-pels — COMMENTED** [review]
When I enter incorrect details, the loader keeps spinning, please fix that. And also, Google and Facebook authentication is dormant. Add Iem of padding to the form.

**Comment by thatkazuk1** [comment]
Squash your commits
🏃 🏃 🏃

**Review by John-pels — DISMISSED** [review]
image
The loader still visible after the error message is being displayed. Also, please add some padding around the form and make the Facebook and Google authentication work!

**Review by Joggz — COMMENTED** [review]
- I have seen the basic functionality work, the loader on the button keeps on loading even after the inputs has been focused on, perhaps you can set a time out for the loader and focus back on the input so to make it easier for the user to access the form and also clear the  please fill in text too

**Review by Mlg29 — COMMENTED** [review]
LGTM. But the sign up with facebook and google are not clicking. Also when u click on log in button after inserting the email and password, if shown invalid email and password, the button still keep loading like rotating after displayin invalid login

**Review by Joggz — COMMENTED** [review]
LGTM, message pops up on log in in with empty field

**Review by John-pels — APPROVED** [review]
LGTM, get others to review it.

**Review by Midetech — CHANGES_REQUESTED** [review]
Good job ma'am but to make it great, I have few things you probably needs to do before considering merge.

image

Check the review from the image above.

Generally, I think you could authenticate all the things that need to be auth so we can have all working page(s) as the case may be. 

All of these are IMO.✌✌✌

**Comment by bamiogunfemi** [comment]
> Good job ma'am but to make it great, I have few things you probably needs to do before considering merge.
> 
> image
> 
> Check the review from the image above.
> 
> Generally, I think you could authenticate all the things that need to be auth so we can have all working page(s) as the case may be.
> 
> All of these are IMO.✌✌✌

Hey the Loader still works its just very fast. Auth for signin with social media isnt ready yet. I'll work on the remaning feedbacks. Thanks

**Comment by lario0913** [comment]
the Forgot Password, Signup, auth with facebook and email arent working ma'am

**Comment by bamiogunfemi** [comment]
> the Forgot Password, Signup, auth with facebook and email arent working ma'am

Routing is yet to be implemented. Socialmedia auth isn't ready

**Comment by Joggz** [comment]
> > the Forgot Password, Signup, auth with facebook and email arent working ma'am
> 
> Routing is yet to be implemented. Socialmedia auth isn't ready

**Pull request closed without merging**
