### PR TITLE
add resturant search page

### PR DESCRIPTION
**Pull request by Joggz**
# What does this PR do?
- display the resturant search page

#Screenshot
- 
Screenshot (190)
Screenshot (191)
Screenshot (192)
Screenshot (193)

### CODE REVIEW

**Review by bamiogunfemi — APPROVED** [review]
LGTM

**Review by John-pels — COMMENTED** [review]
Work on the mobile responsiveness.

**Review by Mlg29 — COMMENTED** [review]
Nice work boss. u still need to adjust a few thing.
1) the Gap between the login button and the icon beside it is too wide, it wasnt like that on my landing page. i dont knw why it appear like that on yours.
2) You need to make use of the colour in our figma design for the button. all colour suppose to be yellow.
3)The search for food input need to align with the text above it.
4)for the minimum order amount, i thought the range input suppose to work with the text. ie as the range moves, the max-order also need to me. i don't know.
5) The same thing applies to the rating. since we are dealing with a dynamic web app, i think the rating should also be dynamic and not static. U can reach out to femi for the rating, i believe he did something on the rating.

Overall nice job boss

**Comment by bamiogunfemi** [comment]
Please rebase and work on the comments.

**Pull request closed without merging**
