### PR TITLE
Payment-Page UI

### PR DESCRIPTION
**Pull request by John-pels**
Payment Page UI done.

payment-page

### CODE REVIEW

**Review by bamiogunfemi — CHANGES_REQUESTED** [review]
Awesome. A little margin from the left and
image
This should be centred
. Happy holidays :blush:

**Review by Mlg29 — COMMENTED** [review]
LGTM. But i noticed that the review your order, payment and done, need to be clickable. ie after the review of order, it roll over to payment page and to do.

**Review by Midetech — COMMENTED** [review]
I honestly must a kudos for great job. Responsiveness LGTM but I have just small feedbacks
1. 
image

2.
image

With this done. You're the chief. Thanks

**Comment by John-pels** [comment]
> Awesome. A little margin from the left and
> image
> This should be centred
> . Happy holidays

The component would be changed as soon as I get it from Muhktar

**Comment by John-pels** [comment]
> LGTM. But i noticed that the review your order, payment and done, need to be clickable. ie after the review of order, it roll over to payment page and to do.

When I say UI, it means the interface, when the other components for Review order and Done are ready then we can talk about that making it interactive.

**Comment by John-pels** [comment]
> Awesome. A little margin from the left and
> image
> This should be centred
> . Happy holidays

I'll change this component and use that of Muhktar, that fits in well into this page.

**Comment by John-pels** [comment]
> I honestly must a kudos for great job. Responsiveness LGTM but I have just small feedbacks
> 1.
> image
> 
> 
> image
> 
> With this done. You're the chief. Thanks

I get the progress you are talking about and to implement this, all other components are needed to communicate with the backend.

**Review by Joggz — CHANGES_REQUESTED** [review]
LGTM, nice layouts, just a couple of feedbacks
- the card image is not visible  but it is present in the DOM
- the Order for food component should be centered, placed right below the pay button, make sure to use the right component when it is available
Annotation 2019-12-28 103611

**Comment by John-pels** [comment]
> LGTM, nice layouts, just a couple of feedbacks
> 
> * the card image is not visible  but it is present in the DOM
> * the Order for food component should be centered, placed right below the pay button, make sure to use the right component when it is available
>   Annotation 2019-12-28 103611

I have just checked the card-image now and it's okay just that you would need internet to load the image from cloudinary. And talking about the Order for food, I'll use that of @Mlg29's component and that will complement everything. Thanks!

**Pull request merged**
