### PR TITLE
set up app routing

### PR DESCRIPTION
**Pull request by bamiogunfemi**

### CODE REVIEW

**Review by Mlg29 — COMMENTED** [review]
LGTM

**Comment by John-pels** [comment]
Please rebase

**Review by Joggz — APPROVED** [review]
Looks Good ...

**Comment by bamiogunfemi** [comment]
> Please rebase

Done

**Review by John-pels — APPROVED** [review]
LGTM!

**Comment by zainaboyedeji** [comment]
LGTM.

**Pull request merged**
