### PR TITLE
Landing page 169566349

### PR DESCRIPTION
**Pull request by Mlg29**
## What Does the PR do ?
-Work on the landing page of the Dae-Alright Project

## Screenshots 
header1
header2
header3
header5
header6
header7

### CODE REVIEW

**Review by John-pels — CHANGES_REQUESTED** [review]
image
Give this section some margin from the top, the text *DOWNLOAD THE APP* has jumped up.

Boss. I don't understand whats going on oo. its perfect on my screen here oo. both desktop and mobile

**Review by John-pels — CHANGES_REQUESTED** [review]
image
Also, remove the overflow-y and set the column to equal size. In addition, there is a box-shadow on each column on hover.

The column are on equal size o. i used grid and they take up equal size. for the box-shadow, on hover there is a box shadow, just that it also have a box-shadow when not hover, thats why it look as if there is no box shadow on hover

**Review by Joggz — COMMENTED** [review]
- heya, you check your browser width, I guess you had zoom in or out while developing this page, so it doesn't look really good on a 100% but looks good on an 80% or 90% browser width
-  the card that holds the food/restaurant name doesn't have a translate on hover, you are supposed to add a box-shadow effect to it when it hovered over
-also, the get more benefit section right below the subscribe to email section should be centered,
- with these fixies, I think we should be good to go.


Boss, the width is 100% and it looks good on my system. maybe u should share a screenshot on how it looks on ur screen

**Comment by bamiogunfemi** [comment]
Please rebase and work on the comments

Done

**Review by Midetech — CHANGES_REQUESTED** [review]
Good job Chief, I just have some few things to make it perfect

**Firstly,**
image

 **Secondly,**
image

**Thirdly,**
image

This is in reference to the above 
image

**Lastly,**
image
Also the gray color isnt that dark. Look into it. 
KINDLY CHECK THE FIGMA THOROUGHLY TO EFFECT THE REQUESTED CHANGES. Thanks

**Review by bamiogunfemi — COMMENTED** [review]
Kindly work on the comments and push by 6pm. Happy Holidays :blush:

**Review by Joggz — CHANGES_REQUESTED** [review]
Hey man, nice work, I will just chip in  little changes to make:
- first: on a 100% browser width, it doesn't look good.
Screenshot (200)
- the image is overflowing it's container
- the image has a border on hover, you should look into that too

Screenshot (202)


- you should look into this part of the page too

Screenshot (203)


In its generality look into your work on the 100% browser width and it should be fine. Good job bro

**Review by John-pels — APPROVED** [review]
Okay, I am merging this PR and we would iterate on it and make it better.

**Pull request merged**
