### PR TITLE
Resturant page

### PR DESCRIPTION
**Pull request by Joggz**
# What does this PR do?
- display the resturant search page

#Screenshot
Screenshot (196)
Screenshot (197)
Screenshot (198)

### CODE REVIEW

**Review by John-pels — CHANGES_REQUESTED** [review]
Nice job! Try to reduce the size of the restaurant names and check the color. This PR would get merged once we get 3 more reviews but please work on the mobile view.

**Review by Midetech — CHANGES_REQUESTED** [review]
Firstly, Good Job chief. But I have few feedbacks. Kindly look into the style guide and make use of the given font and check the style properties for each object on the figma.

image


image


image


Also the responsiveness.

**Comment by Joggz** [comment]
> Nice job! Try to reduce the size of the restaurant names and check the color. This PR would get merged once we get 3 more reviews but please work on the mobile view.

Done, changed the font-size and color of the resturant names

**Review by John-pels — APPROVED** [review]
LGTM, please rebase and remove the component from App.js. Also, clear unwanted codes.

**Comment by Joggz** [comment]
> LGTM, please rebase and remove the component from App.js. Also, clear unwanted codes.

Done, resolved all conflicts and removed all unwanted codes

**Review by bamiogunfemi — APPROVED** [review]
LGTM

**Pull request merged**
